### ISSUE TITLE
jfuns2d corner case

### ISSUE THREAD

**Issue by inducer** [zgimbutas/fmmlib2d#1]
If `nterms.eq.0` (which is not explicitly forbidden), [this line](https://github.com/zgimbutas/fmmlib2d/blob/master/src/cdjseval2d.f#L113) causes an out-of-bounds write.

@sj90101

**Comment by zgimbutas** [comment]
Ha, issue #1!  This code has been known to violate the arrays bounds - nterms, ntop variables, the length of arrays has to be set up to at least nterms+2 (we use ntemrs+5 to be safe) elements. Should we clean the code?

**Comment by inducer** [comment]
Up to you. Shidong ran into it through the Python wrapper and got a mystifying crash.

**Comment by zgimbutas** [comment]
Thanks!

**Comment by zgimbutas** [comment]
Submit fixes to develop branch. Close #1
