### ISSUE TITLE
Error while compiling library

### ISSUE THREAD

**Issue by yosinlpet** [zgimbutas/fmmlib2d#2]
When trying to test the library with `make test`, many errors were thrown in print statements.
I'm compiling with gfortran (gcc 10.2.0)

So I tried to change my default fortran compilator by adding the flag `-std=f95` in the make files, thinking my default gfortran compilator is too recent.
Which did not work either. And neither did the flag `-std=f2008`.

Am I missing something ?

**Comment by zgimbutas** [comment]
gfortran-10 has obsoleted perfectly valid Fortran77 and Fortran90 codes,
that use argument type mismatch. It is possible to turn the support back on
by using -std=legacy command line flag. Please let me know, if that fixes
this issue.

https://github.com/zgimbutas/nufft2d/issues/1

**Comment by yosinlpet** [comment]
It does work; all the errors just became warnings. Thanks for the help!
