### ISSUE TITLE
Original matlab code for zfmm2dparttarg

### ISSUE THREAD

**Issue by TimDeBauw1** [zgimbutas/fmmlib2d#3]
Hey,

I am trying to develop an implementation where your functions of zfmm2d are used to calculate conformal mappings. This works, but now I want to convert all the matlab code to C/C++ code, with the purpose to use its functionality in other languages like C#.

For this conversion I use Matlab Coder, but because zfmm2d are already converted to C/C++ code to be used in a MEX stub, this is unfortunately not possible.

Is there a way to access the original matlab code for the zfmm2d functions (in particular zfmm2dparttarg), before it was converted to C/C++ code?

Many thanks,

Tim

**Comment by ahbarnett** [comment]
I'm a bit confused by your request. We use MEX to interface the fortran library functions to MATLAB. There is no "original matlab code for the zfmm2d functions", rather they are fortran. If you look at makefiles you'll see how it works. In particular, the MEX interface (the only `.c` file in the matlab directory) is actually auto-generated by MWrap, from the `.mw` file. You can install mwrap and try this out.

But I do not know if matlab coder can convert matlab+MEX files to a single binary. Something to try out on a simple mathworks MEX demo code first. Best, Alex

**Comment by TimDeBauw1** [comment]
Ah okay I get it now, I mistakenly thought where written in matlab. Thank you for the quick response!
